__version__: 2.0.6
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  is_check_shapes: true
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: Resize
    height: 640
    interpolation: 1
    mask_interpolation: 0
    p: 1.0
    width: 640
  - __class_fullname__: Normalize
    max_pixel_value: 255.0
    mean:
    - 0.563
    - 0.328
    - 0.244
    normalization: standard
    p: 1.0
    std:
    - 0.315
    - 0.222
    - 0.19
  - __class_fullname__: ToTensorV2
    p: 1.0
    transpose_mask: false
